### ISSUE TITLE
Enhancement: Deselect Hex

### ISSUE THREAD

**Issue by JWhiteUX** [helium/mappers#106] opened 2022-04-05 16:21 UTC
**Problem**
Selecting a hex causes other surrounding hexes to be "selected" or change appearance - indicating mapped hotspots. To select another hex, the user must select an unchanged/unrelated hex, then select the intended hex to display.

**Steps**
Using the latest chrome browser…
1. Zoom to and Select hex
2. Select another hex 
_FAULT_

**Expected Behavior**
Selecting another hex clears the current selection, and displays a new selection.

**Actual Behavior**
Second selection is ignored _UNLESS_ the selected hex is NOT part of the existing selection or related/mapped hex.

**Example**
_Here I am clicking on large yellow hexs, notice how selection only changes when I select a "blue" hex (e.g. a hex without a yellow overlay_

https://user-images.githubusercontent.com/12961108/161800091-8dc25d04-94c3-4c51-8203-b248a6801fdb.mov

**Comment by Siegfried-B** [comment] 2022-04-05 16:40
The issue is known. See issue #95.
As a workaround, closing the info table with the hotspot data list by clicking on the 'x' should clear the selection and highlights. Have you tried this?

**Comment by JWhiteUX** [comment] 2022-04-07 21:43
No I have not tried this. Thank you.

Unfortunately, this workaround is an inadequate solution and fails to address the underlying issue between selection, deselection, and selection interference.

It works, for now, however, is not a long-term solution by any means.

**Comment by Siegfried-B** [comment] 2022-04-16 15:50
Fully agree. The workaround is not a long-term solution and does not solve the underlying issue.

**Closed** 2022-08-02 02:55 UTC
Labels: enhancement
